/*
Redfish OAPI specification

Partial Redfish OAPI specification for a limited client

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// FirmwareInventory struct for FirmwareInventory
type FirmwareInventory struct {
	// The unique identifier for a resource.
	OdataId *string `json:"@odata.id,omitempty"`
}

// NewFirmwareInventory instantiates a new FirmwareInventory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirmwareInventory() *FirmwareInventory {
	this := FirmwareInventory{}
	return &this
}

// NewFirmwareInventoryWithDefaults instantiates a new FirmwareInventory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirmwareInventoryWithDefaults() *FirmwareInventory {
	this := FirmwareInventory{}
	return &this
}

// GetOdataId returns the OdataId field value if set, zero value otherwise.
func (o *FirmwareInventory) GetOdataId() string {
	if o == nil || o.OdataId == nil {
		var ret string
		return ret
	}
	return *o.OdataId
}

// GetOdataIdOk returns a tuple with the OdataId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirmwareInventory) GetOdataIdOk() (*string, bool) {
	if o == nil || o.OdataId == nil {
		return nil, false
	}
	return o.OdataId, true
}

// HasOdataId returns a boolean if a field has been set.
func (o *FirmwareInventory) HasOdataId() bool {
	if o != nil && o.OdataId != nil {
		return true
	}

	return false
}

// SetOdataId gets a reference to the given string and assigns it to the OdataId field.
func (o *FirmwareInventory) SetOdataId(v string) {
	o.OdataId = &v
}

func (o FirmwareInventory) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.OdataId != nil {
		toSerialize["@odata.id"] = o.OdataId
	}
	return json.Marshal(toSerialize)
}

type NullableFirmwareInventory struct {
	value *FirmwareInventory
	isSet bool
}

func (v NullableFirmwareInventory) Get() *FirmwareInventory {
	return v.value
}

func (v *NullableFirmwareInventory) Set(val *FirmwareInventory) {
	v.value = val
	v.isSet = true
}

func (v NullableFirmwareInventory) IsSet() bool {
	return v.isSet
}

func (v *NullableFirmwareInventory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirmwareInventory(val *FirmwareInventory) *NullableFirmwareInventory {
	return &NullableFirmwareInventory{value: val, isSet: true}
}

func (v NullableFirmwareInventory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirmwareInventory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


