/*
Redfish OAPI specification

Partial Redfish OAPI specification for a limited client

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ComputerSystemActions struct for ComputerSystemActions
type ComputerSystemActions struct {
	ComputerSystemReset *ComputerSystemReset `json:"#ComputerSystem.Reset,omitempty"`
}

// NewComputerSystemActions instantiates a new ComputerSystemActions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComputerSystemActions() *ComputerSystemActions {
	this := ComputerSystemActions{}
	return &this
}

// NewComputerSystemActionsWithDefaults instantiates a new ComputerSystemActions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComputerSystemActionsWithDefaults() *ComputerSystemActions {
	this := ComputerSystemActions{}
	return &this
}

// GetComputerSystemReset returns the ComputerSystemReset field value if set, zero value otherwise.
func (o *ComputerSystemActions) GetComputerSystemReset() ComputerSystemReset {
	if o == nil || o.ComputerSystemReset == nil {
		var ret ComputerSystemReset
		return ret
	}
	return *o.ComputerSystemReset
}

// GetComputerSystemResetOk returns a tuple with the ComputerSystemReset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputerSystemActions) GetComputerSystemResetOk() (*ComputerSystemReset, bool) {
	if o == nil || o.ComputerSystemReset == nil {
		return nil, false
	}
	return o.ComputerSystemReset, true
}

// HasComputerSystemReset returns a boolean if a field has been set.
func (o *ComputerSystemActions) HasComputerSystemReset() bool {
	if o != nil && o.ComputerSystemReset != nil {
		return true
	}

	return false
}

// SetComputerSystemReset gets a reference to the given ComputerSystemReset and assigns it to the ComputerSystemReset field.
func (o *ComputerSystemActions) SetComputerSystemReset(v ComputerSystemReset) {
	o.ComputerSystemReset = &v
}

func (o ComputerSystemActions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ComputerSystemReset != nil {
		toSerialize["#ComputerSystem.Reset"] = o.ComputerSystemReset
	}
	return json.Marshal(toSerialize)
}

type NullableComputerSystemActions struct {
	value *ComputerSystemActions
	isSet bool
}

func (v NullableComputerSystemActions) Get() *ComputerSystemActions {
	return v.value
}

func (v *NullableComputerSystemActions) Set(val *ComputerSystemActions) {
	v.value = val
	v.isSet = true
}

func (v NullableComputerSystemActions) IsSet() bool {
	return v.isSet
}

func (v *NullableComputerSystemActions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputerSystemActions(val *ComputerSystemActions) *NullableComputerSystemActions {
	return &NullableComputerSystemActions{value: val, isSet: true}
}

func (v NullableComputerSystemActions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputerSystemActions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


