/*
Redfish OAPI specification

Partial Redfish OAPI specification for a limited client

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// IdRef A reference to a resource.
type IdRef struct {
	// The unique identifier for a resource.
	OdataId *string `json:"@odata.id,omitempty"`
}

// NewIdRef instantiates a new IdRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdRef() *IdRef {
	this := IdRef{}
	return &this
}

// NewIdRefWithDefaults instantiates a new IdRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdRefWithDefaults() *IdRef {
	this := IdRef{}
	return &this
}

// GetOdataId returns the OdataId field value if set, zero value otherwise.
func (o *IdRef) GetOdataId() string {
	if o == nil || o.OdataId == nil {
		var ret string
		return ret
	}
	return *o.OdataId
}

// GetOdataIdOk returns a tuple with the OdataId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdRef) GetOdataIdOk() (*string, bool) {
	if o == nil || o.OdataId == nil {
		return nil, false
	}
	return o.OdataId, true
}

// HasOdataId returns a boolean if a field has been set.
func (o *IdRef) HasOdataId() bool {
	if o != nil && o.OdataId != nil {
		return true
	}

	return false
}

// SetOdataId gets a reference to the given string and assigns it to the OdataId field.
func (o *IdRef) SetOdataId(v string) {
	o.OdataId = &v
}

func (o IdRef) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.OdataId != nil {
		toSerialize["@odata.id"] = o.OdataId
	}
	return json.Marshal(toSerialize)
}

type NullableIdRef struct {
	value *IdRef
	isSet bool
}

func (v NullableIdRef) Get() *IdRef {
	return v.value
}

func (v *NullableIdRef) Set(val *IdRef) {
	v.value = val
	v.isSet = true
}

func (v NullableIdRef) IsSet() bool {
	return v.isSet
}

func (v *NullableIdRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdRef(val *IdRef) *NullableIdRef {
	return &NullableIdRef{value: val, isSet: true}
}

func (v NullableIdRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


